mqtt:
  host: 127.0.0.1
  port: 1883

influxdb:
  host: 127.0.0.1
  port: 8086
  database: node

http:
  destination: https://example.com/content
  action: post
  username: username
  password: password

base64decode:
  source: $.payload.data
  target: data

points:
  - measurement: temperature
    database: my_database
    topic: node/+/thermometer/+/temperature
    fields:
      value: $.payload.data
      decodedvalue: $.base64decoded.data.hex
      foo: 
        value: $.payload.foo
        type: "float"
    tags:
      id: $.topic[1]
      channel: $.topic[3]
    httpcontent:
      frame: $.base64decoded.data.hex
      skipBytes: "1"
  - measurement: hourly_temperature_fahrenheit
    database: my_database
    topic: node/+/thermometer/+/temperature
    # Schedule support:
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12)
    #         │ │ │ │ ┌───────────── day of week (0 - 6) (Sunday to Saturday;
    #         │ │ │ │ │                                       7 is also Sunday on some systems)
    #         │ │ │ │ │
    #         │ │ │ │ │
    #         * * * * *
    schedule: 0 * * * *
    # The formats currently supported are
    #
    #    */5 (for "every X" function),
    #    4-10 (for time ranges),
    #    6,8,23 (for a list of values),
    #    * (for wildcard),
    #    and of course a single number.
    fields:
      value: = 32 + ($.payload.data * 9 / 5)
